name: Deploy Application Template

inputs:
  service_name:
    description: 'Service name'
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  
  - name: print
    shell: bash
    run: echo ${{ inputs.service_name }}
