name: delete

on:
  workflow_dispatch:

jobs:
  delete-unused-cloud-run-sandbox:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Get Git Branches
        run: |
             git branch -a --format='%(refname:short)' > branches.txt
             sed -i 's|origin/||g' branches.txt
      
      - name: Print
        run: cat branches.txt
