name: delete

on:
  workflow_dispatch:

jobs:
  delete-unused-cloud-run-sandbox:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Get Git Branches
        run: |
             git branch -a --format='%(refname:short)' > all_branches.txt
             sed -i 's|origin/||g; s/main//g' all_branches.txt
             cat all_branches.txt | sed -E 's/^(feature|fix|hotfix)\/(.*)/\2/' > branches.txt
        
      - name: Print
        run: cat branches.txt
