name: Manual App Deploy

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service Names'
        required: true
        type: choice
        options:
        - wom
        - ill

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v4
    - name: branch name
      run: echo Branch name ${{ github.ref }}
    - name: stage
      uses: ./.github/template/
      with:
        service_name: ${{ inputs.service_name }}
