name: Manual App Deploy

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service Names'
        required: true
        type: choice
        options:
        - wom
        - ill

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v4
    - name: env name branch
      run: |
           echo "app_name=$(echo "${{ github.ref_name }}" | sed -E 's/^(feature|fix|hotfix)\/(.*)/\2/')" >> "$GITHUB_ENV"
    - name: branch name
      run: |
           branch=$(echo ${{ github.ref }}  | cut --complement -d "/" -f 1-2)
           echo $branch
           echo ${{ env.app_name }}
    - name: stage
      uses: ./.github/template/
      with:
        service_name: ${{ inputs.service_name }}
