name: Deploy application

on:
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          wom: 'wom/**'
          ill: 'ill/**'
    - name: wom
      if: steps.changes.outputs.wom == 'true'
      uses: actions/checkout@v4
    - name: Run packages/utils tests
      if: steps.changes.outputs.ill == 'true'
      uses: actions/checkout@v4
