name: Deploy Application Template

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Service name'
        required: true
        type: string
      environment:
        description: 'environment'
        required: true
        type: string

jobs:
  cloud-run-deploy-job:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: feature/workshop
  
    - name: Installing packages in root directory
      run: echo ${{ inputs.service_name }}
